Created React/Input component
RTUITLab/ITLab-Core-Lib pull request #19
Opened 2022-07-27 14:32 UTC by Zayac11

2022-07-28 06:52 UTC, baikinkirill requested changes

2022-07-28 06:52 UTC, baikinkirill commented on libs/react/ui-core/src/lib/input/useInput.ts
> +  const [hovered, setHovered] = useState<boolean>(false)
Почему тут нельзя было обойтись просто scss? Примеры на скриншоте (17 - 23 строки)

![image](https://user-images.githubusercontent.com/10910903/181438809-09850c47-e2b6-46b8-a28c-f632e42d5689.png)

2022-07-28 06:57 UTC, baikinkirill commented
Так же просто комментарий)

Можно делать вот так, чтобы не писать много строк с `props`:
![image](https://user-images.githubusercontent.com/10910903/181440217-30727aea-c129-48d9-a70b-916228a78f31.png)

`className` подчеркивается красным, так как он дублируется внутри `props`. Можно написать функцию, которая выхватывает только нужные ключи из объекта.

Это чисто вкусовщина на самом деле, с другой стороны оператор spread может кому-то мешать

2022-07-28 08:31 UTC, Zayac11 commented on libs/react/ui-core/src/lib/input/useInput.ts
> +  const [hovered, setHovered] = useState<boolean>(false)
Действительно можно) Там у меня свои приколы были, но я всё обошел

2022-07-28 08:33 UTC, Zayac11 commented
Ну вообще можно было прокидывать `props` как ты предложил, так и строк кода меньше будет, но мне всё же нравится больше, когда всё наглядно видно

2022-07-29 19:41 UTC, baikinkirill approved these changes

2022-08-08 11:11 UTC, merged