Added arrow to horizontal layout + fixed pointer on disabled item
RTUITLab/ITLab-Core-Lib pull request #30
Opened 2022-08-18 22:46 UTC by temchik00

2022-08-19 06:28 UTC, Zayac11 commented
При горизонтальном типе не работает `defaultOpenedItems`. Это так изначально задумано или не? @baikinkirill

2022-08-19 06:49 UTC, Zayac11 requested changes

2022-08-19 06:49 UTC, Zayac11 commented on styles/components/navigation/index.scss
> +        }
Я тоже не придумал как можно красиво выкрутиться, оставив `extend`, но чтобы не дублировать код, можно просто в `325` строчке к классу `.navigation-item-content-open` через запятую прописать `.navigation-item-content .navigation-item-content-label &:hover`

2022-08-19 13:58 UTC, baikinkirill commented
> При горизонтальном типе не работает `defaultOpenedItems`. Это так изначально задумано или не? @baikinkirill

Да

2022-08-24 09:18 UTC, baikinkirill approved these changes

2022-08-25 16:31 UTC, TheDim0n approved these changes

2022-08-25 16:31 UTC, merged