Created React/Badge
RTUITLab/ITLab-Core-Lib pull request #31
Opened 2022-08-18 22:47 UTC by temchik00

2022-08-19 06:24 UTC, Zayac11 requested changes

2022-08-19 06:24 UTC, Zayac11 commented on libs/react/ui-core/src/lib/badge/BadgeProps.d.ts
> +}
В пропсах лучше заменить `text` на `children`. Просто переименовать и прописать тип `string | React.ReactNode;`

2022-08-19 06:24 UTC, Zayac11 commented on libs/react/ui-core/src/lib/badge/badge.tsx
> +    </span>
Ну и здесь получится `{props.children}`

2022-08-24 09:16 UTC, baikinkirill approved these changes

2022-08-25 08:44 UTC, Zayac11 approved these changes

2022-08-25 16:34 UTC, TheDim0n approved these changes

2022-08-25 17:15 UTC, merged