Fixes React/Input component
RTUITLab/ITLab-Core-Lib pull request #32
Opened 2022-08-19 06:13 UTC by Zayac11

2022-08-24 21:42 UTC, temchik00 approved these changes

2022-08-25 16:51 UTC, TheDim0n requested changes
- Убрать выделение предыдущего выбранного значение в календаре
![image](https://user-images.githubusercontent.com/50104612/186722549-06b7dc3a-691b-40a1-9bf8-412ec5badbcd.png)
- У `small` размера календаря сделать шрифт дат не 16, а 14px

2022-08-26 08:29 UTC, baikinkirill requested changes
Я бы календарь вынес как отдельный компонент, чтобы его можно было и в тултип пихать, и просто в различные ~~щели~~ места 

UPD
Пойду почитаю статейки и обязательно когда-нибудь вернусь

2022-08-26 08:29 UTC, baikinkirill commented on libs/react/ui-core/src/lib/input/input.tsx
> +      <div className={`${classes}`} ref={calendar} style={props.style}>
Лучше написать `className={classes}`

2022-08-26 08:29 UTC, baikinkirill commented on libs/react/ui-core/src/lib/input/input.tsx
> +                 disabled={(props.disabled !== undefined && props.disabled)}
Тут можно упростить через `&&`

2022-08-26 08:29 UTC, baikinkirill commented on libs/react/ui-core/src/lib/input/input.tsx
>    </>
Лучше вынести в отдельные компоненты внутри `input.tsx`

https://isamatov.com/react-antipatterns/#declaring-components-inside-of-components

2022-08-26 08:29 UTC, baikinkirill commented on libs/react/ui-core/src/lib/input/useInput.ts
> +  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
useCallback

2022-08-26 08:29 UTC, baikinkirill commented on libs/react/ui-core/src/lib/input/useInput.ts
> +  const handleSelectDate = (date: Date | string) => {
useCallback

2022-08-26 08:29 UTC, baikinkirill commented on libs/react/ui-core/src/lib/input/useInput.ts
> +  const handleClickOutside = (event: any) => {
useCallback

2022-08-26 08:29 UTC, baikinkirill commented on libs/react/ui-core/src/lib/input/useInput.ts
> +  const handleClick = (e: React.MouseEvent<HTMLInputElement>) => {
useCallback

2022-08-26 08:29 UTC, baikinkirill commented on libs/react/ui-core/src/lib/input/calendar/calendar.tsx
> +    <div className={`${styles['calendar']} ${size === 'small' ? styles['calendar-small'] : ''}`}>
Можно просто `size === 'small' && styles['calendar-small']`

2022-08-26 08:29 UTC, baikinkirill commented on libs/react/ui-core/src/lib/input/calendar/calendar.tsx
> +      <span className={`${styles['calendar-icon']}`} onClick={prevMonth}><i className='ri-arrow-left-s-line' /></span>
У нас есть `<Icon />`

2022-08-26 08:29 UTC, baikinkirill commented on libs/react/ui-core/src/lib/input/calendar/calendar.tsx
> +      <span className={`${styles['calendar-icon']}`} onClick={nextMonth}><i className='ri-arrow-right-s-line' /></span>
У нас есть `<Icon />` x2

2022-08-26 08:29 UTC, baikinkirill commented on libs/react/ui-core/src/lib/input/calendar/calendar.tsx
> +}
Стоит вынести в `.d.ts`

2022-08-26 08:29 UTC, baikinkirill commented on libs/react/ui-core/src/lib/input/calendar/calendar.tsx
> +  }
for в компоненте без `useMemo или useEffect`?

2022-08-26 08:29 UTC, baikinkirill commented on libs/react/ui-core/src/lib/input/calendar/calendar.tsx
> +}
`.d.ts`

2022-08-26 08:29 UTC, baikinkirill commented on libs/react/ui-core/src/lib/input/calendar/calendar.tsx
> +  const startDate = getMonday(monthStart);
При каждом изменении эти функции будут вызываться заново

2022-08-26 08:29 UTC, baikinkirill commented on libs/react/ui-core/src/lib/input/calendar/calendar.tsx
> +  }
Это плохо для производительности, надо либо `useMemo` или `useEffect`

2022-08-26 08:29 UTC, baikinkirill commented on libs/react/ui-core/src/lib/input/calendar/calendar.tsx
> +}
`.d.ts`

2022-08-26 08:29 UTC, baikinkirill commented on libs/react/ui-core/src/lib/input/calendar/useCalendar.ts
> +export function useCalendar() {
Судя по функционалу — это не хук. Можно было бы сделать объект с функциями, или класс.

2022-08-26 08:29 UTC, baikinkirill commented on libs/react/ui-core/src/lib/input/calendar/calendar.tsx
> +  };
Ух, тяжело...

Возможно стоит в `useCallback`, но я не уверен, я устал :(

P.S. 
этот комментарий я пишу последним после всех остальных, но мб он будет первым

2022-08-26 08:29 UTC, baikinkirill commented on libs/react/ui-core/src/lib/input/calendar/calendar.tsx
> +        {month[currentMonth.getMonth()]} {currentMonth.getFullYear()}
Плохо такие вычисления вызывать прямо в коде

2022-08-26 08:41 UTC, Zayac11 commented on libs/react/ui-core/src/lib/input/calendar/calendar.tsx
> +    <div className={`${styles['calendar']} ${size === 'small' ? styles['calendar-small'] : ''}`}>
В таком случае будет `false`
![image](https://user-images.githubusercontent.com/54433033/186862138-fe1b9614-028b-4bbe-8f0d-01b647f25011.png)

2022-08-27 11:21 UTC, TheDim0n approved these changes

2022-08-29 09:01 UTC, baikinkirill requested changes
После этого можно сливать

2022-08-29 10:20 UTC, Zayac11 commented on libs/react/ui-core/src/lib/calendar/calendar.tsx
> +      "calendar-selected": (CalendarFunctions.isSameDay(day, selectedDate) || (endDate && CalendarFunctions.isSameDay(day, endDate))) || false,
Из-за того, что `endDate` может быть `undefuned` подчеркивает красненьким, крч я поменял просто на `!!endDate`

2022-08-29 10:30 UTC, Zayac11 commented on libs/react/ui-core/src/lib/calendar/calendar.tsx
> +        {weeks[CalendarFunctions.addDays(startDate, i - 1).getDay()]}
При каждом тыке на какую-либо дату, оно мне проверяет все 7 дней каждой недели месяца, чтобы отметить выделенный день, этот цикл уже находится в useMemo. По-моему все работает так, как и должно. Или я чета не понимаю?

2022-08-30 06:49 UTC, baikinkirill approved these changes

2022-08-30 09:01 UTC, merged