Created React/BackTop component
RTUITLab/ITLab-Core-Lib pull request #36
Opened 2022-08-19 19:25 UTC by temchik00

2022-08-22 15:56 UTC, baikinkirill approved these changes

2022-08-23 20:16 UTC, Zayac11 approved these changes

2022-08-25 17:09 UTC, TheDim0n requested changes
Добавить функцию по умолчанию

2022-08-26 07:50 UTC, baikinkirill requested changes
Так и должно плющить? Браузер: `Firefox v103.0.2`

![image](https://user-images.githubusercontent.com/10910903/186849354-b27da22c-7893-4fc6-ae56-3e270e837419.png)

2022-08-26 07:50 UTC, baikinkirill commented on libs/react/ui-core/src/lib/back-top/useBackTop.ts
> +  }
Функции, возвращаемые из хуков должны быть в useCallback

2022-08-26 07:50 UTC, baikinkirill commented on libs/react/ui-core/src/lib/back-top/useBackTop.ts
> +    if (typeof props.className === 'object') classList.push(...props.className);
Вообще, у нас получается очень много дублирования с этими строчками, может вынести их в отдельную функцию в папку `utils`?

2022-08-26 08:13 UTC, Zayac11 commented on libs/react/ui-core/src/lib/back-top/useBackTop.ts
> +    if (typeof props.className === 'object') classList.push(...props.className);
Займусь в следующей версии

2022-08-26 10:56 UTC, baikinkirill approved these changes

2022-08-26 10:56 UTC, baikinkirill commented
Еще можно сделать анимированный скролл наверх:

```
function scrollToTop(){
  window.scrollTo({top: 0, behavior: 'smooth'});
}
```

2022-08-26 14:40 UTC, Zayac11 approved these changes

2022-08-27 11:16 UTC, TheDim0n approved these changes

2022-08-27 11:17 UTC, merged