Created React/Collapse component
RTUITLab/ITLab-Core-Lib pull request #38
Opened 2022-08-24 21:44 UTC by temchik00

2022-08-25 09:11 UTC, Zayac11 requested changes

2022-08-25 09:11 UTC, Zayac11 commented on styles/components/collapse/index.scss
> +}
Аналогично здесь. Плюс необходимо здесь прописать стили для текста, в том числе и цвет, а еще шрифт тут `Times New Roman`.

![image](https://user-images.githubusercontent.com/54433033/186622811-a5b56b0b-80ee-409b-aaf3-c847e5bfa5ae.png)

2022-08-25 09:11 UTC, Zayac11 commented on libs/react/ui-core/src/lib/collapse/collapse.stories.tsx
> +          }}
Дефолтную окраску нужно сделать в классе, а то у пользователя будет просто `#000` цвет.

2022-08-26 07:16 UTC, Zayac11 approved these changes

2022-08-26 07:16 UTC, Zayac11 commented on styles/components/collapse/index.scss
> +}
Тут можно было везде воспользоваться дизайн-токенами

2022-08-26 07:35 UTC, baikinkirill requested changes

2022-08-26 07:35 UTC, baikinkirill commented on libs/react/ui-core/src/lib/collapse/collapse.tsx
> +  );
Вот так объявлять компоненты в компоненте — антипаттерн. Это лучше вынести отдельно, так как при любых изменениях в CollapseItem реакт будет делать ререндер этой иконки.

А вообще, у нас же есть компонент `<Item />` для иконок

2022-08-26 07:35 UTC, baikinkirill commented on libs/react/ui-core/src/lib/collapse/useCollapseItem.ts
> +  }
Функции, возвращаемые из хуков должны быть в `useCallback`

2022-08-26 07:35 UTC, baikinkirill commented on libs/react/ui-core/src/lib/collapse/collapse.tsx
> +      >
Тут можно просто `onClick={toggleExpanded}`

2022-08-26 07:35 UTC, baikinkirill commented on styles/components/collapse/index.scss
> +  line-height: 28px;
По идее все размеры должны быть в дизайн-токенах, но это к дизайнерам

2022-08-26 07:42 UTC, Zayac11 commented on styles/components/collapse/index.scss
> +  line-height: 28px;
Думаю дизайн токены стоит в принципе поправить. Устал уже ручками постоянно писать `line-height: 24px`, когда по токенам там `19px` :)

2022-08-27 11:12 UTC, TheDim0n approved these changes

2022-08-29 09:04 UTC, baikinkirill approved these changes

2022-08-30 09:02 UTC, merged