Created React/Tag component
RTUITLab/ITLab-Core-Lib pull request #47
Opened 2022-08-31 08:59 UTC by Zayac11

2022-09-11 07:19 UTC, TheDim0n requested changes
Поменять отступы у tooltip для удаления тэга

2022-09-14 19:46 UTC, TheDim0n approved these changes

2022-09-14 20:13 UTC, temchik00 approved these changes

2022-09-14 20:51 UTC, baikinkirill approved these changes

2022-10-04 16:12 UTC, merged