Created React/Slider component
RTUITLab/ITLab-Core-Lib pull request #49
Opened 2022-09-01 08:16 UTC by Zayac11

2022-09-11 07:37 UTC, TheDim0n requested changes
Пофиксить step, `style` props и длину InputNumber

2022-09-14 19:49 UTC, TheDim0n approved these changes

2022-09-14 20:24 UTC, temchik00 approved these changes

2022-09-14 21:41 UTC, baikinkirill approved these changes

2022-10-04 16:13 UTC, merged