Created React/Modal component
RTUITLab/ITLab-Core-Lib pull request #50
Opened 2022-09-01 13:42 UTC by temchik00

2022-09-04 09:48 UTC, baikinkirill requested changes
Модальные окна в реакте должны создаваться через [`createPortal`](https://reactjs.org/docs/portals.html).

Модалка должна находиться как можно выше в дереве элементов, чтобы ее ничего не перекрывало. Реализация через `z-index: 3` — костыль, так как элемент уже с `z-index: 4` перекроет модалку.

Выхода два:
- через `document` создавать `div` прямо внутри `body`, и в него уже рендерить через [`createPortal`](https://reactjs.org/docs/portals.html)
- или вообще не реализовывать появление, а оставить только сам компонент, чтобы разработчики как хотят, так и показывают эти окна

2022-09-08 18:17 UTC, Zayac11 requested changes

2022-09-08 18:17 UTC, Zayac11 commented on libs/react/ui-core/src/lib/modal/modal.tsx
> +  }, [props.onClose, props.closeOnBackground]);
Это можно в хук убрать

2022-09-08 18:17 UTC, Zayac11 commented on styles/components/modal/index.scss
> +}
Меня смутил `cursor: poiner`, лучше его убрать и оставить `default`. Никогда не видел у модалки на фоне курсор `pointer`

2022-09-08 18:17 UTC, Zayac11 commented on styles/components/modal/index.scss
> +  left: 50%;
Я бы еще добавил сюда небольшую защиту типа `max-width: calc(100vw - 40px);`

2022-09-11 06:52 UTC, Zayac11 approved these changes

2022-09-11 07:44 UTC, TheDim0n approved these changes

2022-09-14 19:39 UTC, baikinkirill approved these changes

2022-09-14 19:50 UTC, merged