Created React/Timeline component
RTUITLab/ITLab-Core-Lib pull request #58
Opened 2022-09-07 19:53 UTC by Zayac11

2022-09-09 10:24 UTC, Zayac11 commented
Также вынес логику открывания и закрывания контента из компонент `Navigation`, `Collapse` и `Timeline` в отдельный хук `utils/useDropdownItem.ts`

2022-09-11 07:51 UTC, TheDim0n approved these changes

2022-09-14 20:34 UTC, temchik00 approved these changes

2022-09-14 20:58 UTC, baikinkirill requested changes

2022-09-14 20:58 UTC, baikinkirill commented on libs/react/ui-core/src/lib/timeline/timelineItem.tsx
> +  console.log(itemHeight)
Нужно его убрать

2022-09-14 20:58 UTC, baikinkirill commented on libs/react/ui-core/src/lib/navigation/useMenuItem.tsx
> +      }, 2)
Зачем?

2022-09-14 20:58 UTC, baikinkirill commented on libs/react/ui-core/src/lib/collapse/useCollapseItem.ts
> +      "collapse-item-expanded": !!expanded,
Так лучше не делать. Лучше обернуть в `Boolean`

2022-09-14 20:58 UTC, baikinkirill commented on libs/react/ui-core/src/lib/collapse/useCollapseItem.ts
> +      "collapse-item-header-container-expanded": !!expanded,
То же

2022-09-15 08:16 UTC, baikinkirill approved these changes

2022-10-04 16:14 UTC, merged