Created React/Notification component
RTUITLab/ITLab-Core-Lib pull request #60
Opened 2022-09-10 20:15 UTC by temchik00

2022-09-11 08:00 UTC, TheDim0n approved these changes

2022-09-13 10:39 UTC, Zayac11 requested changes

2022-09-13 10:39 UTC, Zayac11 commented on styles/components/notification/index.scss
> +  padding-right: 100px;
Необходимо добавить `z-index`, ситуация как в модалке примерно

Просто эти уведомления перекроет любой элемент с `z-index: 1`
![image](https://user-images.githubusercontent.com/54433033/189877874-39a81d8f-b994-4c39-a84c-3ead50ac9206.png)

2022-09-13 10:39 UTC, Zayac11 commented on libs/react/ui-core/src/lib/notification/NotificationProps.d.ts
> +
Маловато позиций, как минимум нужно добавить позиции по левому краю. `top-left`, `bottom-left`, `top-right` и `bottom-right`

2022-09-14 19:51 UTC, Zayac11 approved these changes

2022-09-15 08:17 UTC, baikinkirill approved these changes

2022-10-04 16:14 UTC, merged