Created React/Steps component
RTUITLab/ITLab-Core-Lib pull request #61
Opened 2022-09-11 00:21 UTC by temchik00

2022-09-11 08:06 UTC, TheDim0n requested changes
Иконки отдельно для каждого step

2022-09-13 10:17 UTC, Zayac11 requested changes
Далее покажу визуальные косяки, которые нужно поправить, думать просто чуть-чуть нужно поиграться с созданным миксином

1. Из иконки линия приходит не в центр обычного кружка (так на всех размерах)

![image](https://user-images.githubusercontent.com/54433033/189874595-68216de6-b5d6-49e6-ab8f-d4e29a4a5c47.png)

2. Нужно как-то пересчитать длину и позицию линии, выходящей из иконки, потому что при выходе всегда есть пробел, а на входе линия всегда протыкает кружок. На дизайне пробелы с обеих сторон, в любом случае нужно сделать хотя бы однообразно, то есть либо с обеих сторон пробелы, либо всегда протыкает.

![image](https://user-images.githubusercontent.com/54433033/189874806-cb06d619-f1c4-495f-9d97-15cb59de53f9.png)

3. Ну и еще к вопросу о пересчете длины линии, у `small` линия проткнула кружок насквозь (чуть-чуть приблизил, чтобы было лучше видно, но при `100%` масштабе тоже заметно)
![image](https://user-images.githubusercontent.com/54433033/189875460-78eda544-637b-44b5-9425-8bdbb9c5df9d.png)

2022-09-13 10:17 UTC, Zayac11 commented on styles/components/steps/index.scss
> +      }
Вот тут у каждого размера добавить `justify-content: center`, т.к. размер у кружка с иконкой всегда меньше, чем у кружка без нее. Нужно выровнять их по высоте, чтобы были на одной линии

2022-09-14 19:53 UTC, TheDim0n approved these changes

2022-09-14 19:55 UTC, Zayac11 approved these changes

2022-09-14 21:21 UTC, baikinkirill approved these changes

2022-10-04 16:15 UTC, merged